apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kvcqjhl4z-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kvcqjhl4z-go 
  name: kvcqjhl4z-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kvcqjhl4z-go 
